apiVersion: v1
name: ia-case-documents-api
home: https://github.com/hmcts/ia-case-documents-api
version: 0.0.10
description: Immigration & Asylum Case Documents Service
maintainers:
  - name: HMCTS Immigration & Asylum Team
    email: ImmigrationandAsylum@HMCTS.NET
