java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devcpuRequests: 1000m
  devmemoryRequests: 1024Mi
  devcpuLimits: 3000m
  devmemoryLimits: 1536Mi
  environment:
    IA_AIP_FRONTEND_URL: "https://immigration-appeal.{{ .Values.global.environment }}.platform.hmcts.net/"
    PAY_CALLBACK_URL: "https://${SERVICE_NAME}-documents-api.preview.platform.hmcts.net/service-request-update"
    IA_EXUI_FRONTEND_URL: "https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net/"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
