apiVersion: v2
name: ia-case-notifications-api
home: https://github.com/hmcts/ia-case-notifications-api
version: 0.0.47
description: Immigration & Asylum Case Notifications Service
maintainers:
  - name: HMCTS Immigration & Asylum Team
    email: ImmigrationandAsylum@HMCTS.NET
dependencies:
  - name: java
    version: 5.0.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
