apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Case Payments API App
name: ia-case-payments-api
home: https://github.com/hmcts/ia-case-payments-api
version: 0.0.25
maintainers:
  - name: Immigration & Asylum Team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
