apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Case Payments API App
name: ia-case-payments-api
home: https://github.com/hmcts/ia-case-payments-api
version: 0.0.6
maintainers:
  - name: Immigration & Asylum Team
